#!/usr/bin/env python3
# =============================================================================
# tools/gen_hershey_font.py -- generate STROKE-font atlases for the
# examples/amazing.trx masking feature from the Hershey vector fonts.
#
# Unlike the bitmap atlases (tools/gen_mask_font.py, which need Pillow), Hershey
# glyphs are single-stroke polylines -- so this tool emits the raw stroke
# COORDINATES as Trix data and amazing.trx renders them in PURE TRIX (stroking
# each centerline with a pen width into the mask).  No Pillow, no FreeType, and
# the result is vector -- crisp at any maze size.
#
# LICENSE: the Hershey glyph DESIGNS were drawn by Dr. A. V. Hershey at the U.S.
# Naval Weapons Laboratory (1967) as U.S.-government work and are in the PUBLIC
# DOMAIN.  This tool re-encodes the public-domain coordinate designs into our
# own compact Trix format (it does not redistribute any restricted .jhf
# compilation verbatim).  Hershey is credited in NOTICE.md; no license travels
# with the emitted data.  The source .jhf is downloaded only to read the PD
# coordinates and is never committed.
#
# HOST TOOLS REQUIRED (only to regenerate -- not to RUN amazing.trx):
#   * Python 3.8+  (standard library only; no third-party deps)
#   * network access (to fetch the .jhf coordinate data)
#
# DEFAULT (no args): writes
#   examples/mask-fonts/hershey-sans.trx     (Roman Simplex -- single stroke)
#   examples/mask-fonts/hershey-serif.trx    (Roman Triplex -- bolder, serifs)
#
#   tools/gen_hershey_font.py --preview "Trix gjpy"   # ASCII preview, no write
# =============================================================================

import argparse
import os
import sys
from urllib.request import urlopen

# style name -> (.jhf source URL, label).  The data are the PD Hershey designs.
STYLES = {
    "hershey-sans":  ("https://raw.githubusercontent.com/kamalmostafa/hershey-fonts/master/hershey-fonts/rowmans.jhf",
                      "Hershey Roman Simplex (public domain)"),
    "hershey-serif": ("https://raw.githubusercontent.com/kamalmostafa/hershey-fonts/master/hershey-fonts/rowmant.jhf",
                      "Hershey Roman Triplex (public domain)"),
}

CELL_H = 36   # target cell height in grid units (strokes are scaled to this)
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(REPO_ROOT, "examples", "mask-fonts")


def parse_jhf(text):
    """Parse a .jhf stream into [(left, right, [polyline,...]), ...] in file
    order.  Each polyline is a list of (x, y) ints in Hershey units (y-down)."""
    lines = text.split("\n")
    glyphs = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip():
            i += 1
            continue
        nvert = int(line[5:8])
        data = line[8:]
        i += 1
        while len(data) < nvert * 2:          # glyph wrapped onto next line
            data += lines[i]
            i += 1
        left = ord(data[0]) - ord("R")
        right = ord(data[1]) - ord("R")
        polys, cur = [], []
        for k in range(1, nvert):
            cx, cy = data[2 * k], data[2 * k + 1]
            if cx == " " and cy == "R":       # pen up -> break the polyline
                if cur:
                    polys.append(cur)
                    cur = []
            else:
                cur.append((ord(cx) - ord("R"), ord(cy) - ord("R")))
        if cur:
            polys.append(cur)
        glyphs.append((left, right, polys))
    return glyphs


def build_font(text):
    """Map the file-order glyphs to printable ASCII (the occidental sets are in
    ASCII order from 0x20), normalise to CELL_H, return {ch: (advance, polys)}."""
    raw = parse_jhf(text)
    # global vertical extent across all glyphs (for a shared baseline + box)
    ys = [y for (_, _, polys) in raw for poly in polys for (_, y) in poly]
    ymin, ymax = min(ys), max(ys)
    scale = CELL_H / (ymax - ymin)
    out = {}
    for idx, (left, right, polys) in enumerate(raw):
        ch = chr(0x20 + idx)
        if ord(ch) > 0x7E:
            break
        adv = max(1, round((right - left) * scale))
        sp = [[(round((x - left) * scale), round((y - ymin) * scale)) for (x, y) in poly]
              for poly in polys]
        out[ch] = (adv, sp)
    return out


def emit_trix(name, label, font):
    out = ["% " + "=" * 75,
           "%  GENERATED by tools/gen_hershey_font.py -- DO NOT EDIT BY HAND.",
           f"%  Font:    {label}",
           "%  Kind:    stroke font (public-domain Hershey designs, re-encoded)",
           f"%  Cell height: {CELL_H} units   Glyphs: {len(font)} (printable ASCII)",
           "%",
           "%  Registers into MASK-FONTS (created by amazing.trx).  (kind) is (stroke);",
           "%  each glyph is [advance [ poly... ]] and each poly is a flat [x0 y0 x1 y1",
           "%  ...] centerline.  amazing.trx strokes them with a pen width into the mask.",
           "% " + "=" * 75,
           f"MASK-FONTS ({name}) <<",
           "    (kind) (stroke)",
           f"    (h) {CELL_H}",
           "    (pen) 2",
           "    (glyphs) <<"]
    for ch in [chr(c) for c in range(0x20, 0x7F)]:
        if ch not in font:
            continue
        adv, polys = font[ch]
        key = "(\\" + ch + ")" if ch in "()\\" else "(" + ch + ")"
        body = " ".join("[ " + " ".join(f"{x} {y}" for (x, y) in poly) + " ]" for poly in polys)
        out.append(f"        {key:8} [ {adv} [ {body} ] ]")
    out += ["    >>", ">> put", ""]
    return "\n".join(out)


def preview(font, word):
    W = sum(font.get(c, (8, []))[0] for c in word) + 4
    grid = [[" "] * W for _ in range(CELL_H + 1)]
    pen = 0
    for c in word:
        adv, polys = font.get(c, (8, []))
        for poly in polys:
            for j in range(len(poly) - 1):
                x0, y0 = poly[j]
                x1, y1 = poly[j + 1]
                steps = max(abs(x1 - x0), abs(y1 - y0), 1)
                for s in range(steps + 1):
                    x = round(x0 + (x1 - x0) * s / steps) + pen
                    y = round(y0 + (y1 - y0) * s / steps)
                    if 0 <= y <= CELL_H and 0 <= x < W:
                        grid[y][x] = "#"
        pen += adv
    print("\n".join("".join(r) for r in grid))


def main():
    ap = argparse.ArgumentParser(description="Generate Trix stroke mask-fonts from Hershey (PD).")
    ap.add_argument("--preview", help="ASCII-preview a word and exit (no files written)")
    ap.add_argument("--out-dir", default=OUT_DIR)
    args = ap.parse_args()
    os.makedirs(args.out_dir, exist_ok=True)

    if args.preview:
        text = urlopen(STYLES["hershey-sans"][0], timeout=60).read().decode("latin-1")
        preview(build_font(text), args.preview)
        return

    for name, (url, label) in STYLES.items():
        print(f"fetching {label} ...", file=sys.stderr)
        text = urlopen(url, timeout=60).read().decode("latin-1")
        font = build_font(text)
        path = os.path.join(args.out_dir, f"{name}.trx")
        open(path, "w").write(emit_trix(name, label, font))
        print(f"wrote {path} ({len(font)} glyphs)")


if __name__ == "__main__":
    main()
